#pragma once

enum class KodStatus : uint32_t
{
    KODSTATUS_SUCCESS = 0,

    // FileUtils
    KODSTATUS_FILEUTILS_READ_WHOLE_FILE_COULDNT_OPEN_FILE,

    // Lexer
    KODSTATUS_LEXER_GET_CURRENT_CHAR_INDEX_OUT_OF_RANGE,
    KODSTATUS_LEXER_PEEK_CHAR_INDEX_OUT_OF_RANGE,
    KODSTATUS_LEXER_GET_NEXT_TOKEN_UNKNOWN_CHARARCTER,
    KODSTATUS_LEXER_COLLECT_STRING_UNTERMINATED_STRING,
};
